version: "3.8"
services:
  server:
    container_name: "conversor-server"
    image: "conversor/server"
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
